# Analyzing data from Task 1

Note to self: trying to run `cmdstanpy` on windows is quite painful ... let's try to keep the workflow mostly in MacOS ...

In [2]:
import polars as pl
import pandas as pd
import pymc as pm
import arviz as az
import arviz_plots as azp
import os 
import shutil 
import cmdstanpy 
from cmdstanpy import CmdStanModel
from cmdstanpy import cmdstan_path
print(f'cmdstan is installed at {cmdstan_path()}')

cmdstan is installed at /Users/shenglong/.cmdstan/cmdstan-2.38.0

In [3]:
# read in data 
task1_df = pl.read_csv("../../data/processed/task1.csv")
task1_df.head()

shape: (5, 27)
┌─────┬──────────────────────────┬───────┬─────┬───┬───────────┬─────────────┬──────────┬──────────┐
│     ┆ participantId            ┆ task  ┆ id  ┆ … ┆ phy.mod.x ┆ va.select.x ┆ va.med.x ┆ va.mod.x │
│ --- ┆ ---                      ┆ ---   ┆ --- ┆   ┆ ---       ┆ ---         ┆ ---      ┆ ---      │
│ i64 ┆ str                      ┆ str   ┆ i64 ┆   ┆ f64       ┆ f64         ┆ f64      ┆ f64      │
╞═════╪══════════════════════════╪═══════╪═════╪═══╪═══════════╪═════════════╪══════════╪══════════╡
│ 1   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 1   ┆ … ┆ 62.920652 ┆ 5.321116    ┆ 5.368009 ┆ 5.390766 │
│ 2   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 2   ┆ … ┆ 50.592391 ┆ 5.072333    ┆ 5.171459 ┆ 4.335665 │
│ 3   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 3   ┆ … ┆ 63.036957 ┆ 5.321116    ┆ 5.257493 ┆ 5.400716 │
│ 4   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 4   ┆ … ┆ 47.801087 ┆ 5.072333    ┆ 5.165791 ┆ 4.096666 │
│ 5   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 5   ┆ … ┆ 53.848913 ┆ 4.554715    ┆ 4.496682 ┆ 4.61445  │
└─────┴──────────────────────────┴───────┴─────┴───┴───────────┴─────────────┴──────────┴──────────┘

Get the data ready for stan:

In [38]:
numeric_id = task1_df.select(pl.col('participantId').cast(pl.Categorical).to_physical()).to_numpy().flatten()
# make sure the ids are not 0-indexed 
numeric_id += 1 

stan_data = {
    'N': task1_df.height, 
    'J': task1_df.select(pl.col('participantId')).n_unique(), 
    'id': numeric_id, 
    'x': task1_df.select('va.select.x').to_numpy().flatten(), 
    'x_med': task1_df.select('va.med.x').to_numpy().flatten(),
    'x_mod': task1_df.select('va.mod.x').to_numpy().flatten()
}

# stan_data

# Compile stan models

## `task1.weighted.avg.stan` 

- centered parameterization

In [39]:
task1_mix_stanfile = os.path.join('../stan_files/', "task1.weighted.avg.stan")
task1_model = CmdStanModel(stan_file=task1_mix_stanfile)

In [40]:
# use shutil to move things around
dest_dir = "../stan_bin_files"
shutil.move(task1_model.exe_file, os.path.join(dest_dir, task1_model.name))
task1_model = CmdStanModel(exe_file=os.path.join(dest_dir, task1_model.name))

In [44]:
# sample 
fit1 = task1_model.sample(
    data = stan_data, 
    chains=4, 
    parallel_chains=4, 
    iter_warmup=2000,
    iter_sampling=4000,
    adapt_delta=0.99, 
    show_console=False, 
)

12:50:08 - cmdstanpy - INFO - CmdStan start processing
chain 1:   0%|          | 0/6000 [00:00<?, ?it/s, (Warmup)]


chain 1:   2%|▏         | 100/6000 [00:01<01:23, 70.90it/s, (Warmup)]


chain 1:   3%|▎         | 200/6000 [00:01<00:46, 125.34it/s, (Warmup)]

chain 1:   5%|▌         | 300/6000 [00:01<00:30, 189.53it/s, (Warmup)]


chain 1:   7%|▋         | 400/6000 [00:02<00:23, 241.44it/s, (Warmup)]



chain 1:   8%|▊         | 500/6000 [00:02<00:21, 258.41it/s, (Warmup)]

chain 1:  10%|█         | 600/6000 [00:02<00:17, 315.29it/s, (Warmup)]

chain 1:  12%|█▏        | 700/6000 [00:02<00:14, 362.68it/s, (Warmup)]

chain 1:  13%|█▎        | 800/6000 [00:03<00:12, 404.64it/s, (Warmup)]

chain 1:  15%|█▌        | 900/6000 [00:03<00:11, 447.33it/s, (Warmup)]



chain 1:  18%|█▊        | 1100/6000 [00:04<00:14, 347.41it/s, (Warmup)]
chain 1:  20%|██        | 1200/6000 [00:04<00:12, 371.98it/s, (Warmup)]
chain 1:  22%|██▏       | 1300/6000 [00:04<00:11, 399.26it/s, (Warmup)]

chain 1:  23%|██▎       | 1400/6000 [00:04<00:10, 446.31it/s, (Warmup)]
chain 1:  25%|██▌       | 1500/6000 [00:04<00:10, 431.32it/s, (Warmup)]


chain 1:  27%|██▋       | 1600/6000 [00:05<00:10, 419.74it/s, (Warmup)]

chain 1:  28%|██▊       | 1700/6000 [00:05<00:09, 437.49it/s, (Warmup)]

chain 1:  30%|███       | 1800/6000 [00:05<00:09, 461.10it/s, (Warmup)]



chain 1:  32%|███▏      | 1900/6000 [00:05<00:11, 357.88it/s, (Warmup)]






chain 1:  33%|███▎      | 2000/6000 [00:06<00:19, 205.04it/s, (Sampling)]






chain 1:  35%|███▌      | 2100/6000 [00:07<00:18, 212.96it/s, (Sampling)]




chain 1:  37%|███▋      | 2200/6000 [00:07<00:17, 222.98it/s, (Sampling)]



chain 1:  38%|███▊      | 2300/6000 [00:08<00:15, 236.85it/s, (Sampling)]




chain 1:  40%|████      | 2400/6000 [00:08<00:15, 226.68it/s, (Sampling)]




chain 1:  42%|████▏     | 2500/6000 [00:09<00:15, 227.70it/s, (Sampling)]




chain 1:  43%|████▎     | 2600/6000 [00:09<00:14, 230.91it/s, (Sampling)]




chain 1:  45%|████▌     | 2700/6000 [00:09<00:14, 233.01it/s, (Sampling)]





chain 1:  47%|████▋     | 2800/6000 [00:10<00:13, 231.72it/s, (Sampling)]




chain 1:  48%|████▊     | 2900/6000 [00:10<00:13, 227.94it/s, (Sampling)]




chain 1:  50%|█████     | 3000/6000 [00:11<00:13, 226.61it/s, (Sampling)]





chain 1:  52%|█████▏    | 3100/6000 [00:11<00:13, 216.03it/s, (Sampling)]





chain 1:  53%|█████▎    | 3200/6000 [00:12<00:13, 210.12it/s, (Sampling)]



chain 1:  55%|█████▌    | 3300/6000 [00:12<00:12, 219.12it/s, (Sampling)]





chain 1:  57%|█████▋    | 3400/6000 [00:13<00:11, 218.77it/s, (Sampling)]





chain 1:  58%|█████▊    | 3500/6000 [00:13<00:10, 227.85it/s, (Sampling)]





chain 1:  60%|██████    | 3600/6000 [00:13<00:10, 228.57it/s, (Sampling)]





chain 1:  62%|██████▏   | 3700/6000 [00:14<00:10, 223.93it/s, (Sampling)]



chain 1:  63%|██████▎   | 3800/6000 [00:14<00:09, 227.35it/s, (Sampling)]





chain 1:  65%|██████▌   | 3900/6000 [00:15<00:09, 228.75it/s, (Sampling)]





chain 1:  67%|██████▋   | 4000/6000 [00:15<00:08, 242.19it/s, (Sampling)]






chain 1:  68%|██████▊   | 4100/6000 [00:16<00:07, 247.07it/s, (Sampling)]


chain 1:  70%|███████   | 4200/6000 [00:16<00:07, 245.90it/s, (Sampling)]




chain 1:  72%|███████▏  | 4300/6000 [00:16<00:06, 243.45it/s, (Sampling)]

chain 1:  73%|███████▎  | 4400/6000 [00:17<00:06, 254.87it/s, (Sampling)]

chain 1:  75%|███████▌  | 4500/6000 [00:17<00:06, 222.44it/s, (Sampling)]

chain 1:  77%|███████▋  | 4600/6000 [00:18<00:05, 235.94it/s, (Sampling)]
chain 1: 100%|██████████| 6000/6000 [00:23<00:00, 258.89it/s, (Sampling completed)]
chain 2: 100%|██████████| 6000/6000 [00:23<00:00, 258.89it/s, (Sampling completed)]

chain 3: 100%|██████████| 6000/6000 [00:23<00:00, 258.92it/s, (Sampling completed)]


chain 4: 100%|██████████| 6000/6000 [00:23<00:00, 258.91it/s, (Sampling completed)]

12:50:31 - cmdstanpy - INFO - CmdStan done processing.
12:50:31 - cmdstanpy - WARNING - Non-fatal error during sampling:
Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in 'task1.weighted.avg.stan', line 57, column 4 to column 47)
	Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in 'task1.weighted.avg.stan', line 57, column 4 to column 47)
	Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in 'task1.weighted.avg.stan', line 57, column 4 to column 47)
Exception: lognormal_lpdf: Scale parameter is inf, but must be positive finite! (in 'task1.weighted.avg.stan', line 58, column 4 to column 67)
	Exception: lognormal_lpdf: Scale parameter is inf, but must be positive finite! (in 'task1.weighted.avg.stan', line 58, column 4 to column 67)
	Exception: task1x46weightedx46avg_model_namespace::log_prob: theta[21] is nan, but must be greater than or equal to 0.000000 (in 'task1.weighted.avg.stan', line 31, column 2 to column 36)
Exception: lognormal_lpdf: Scale parameter is inf, but must be positive finite! (in 'task1.weighted.avg.stan', line 58, column 4 to column 67)
	Exception: lognormal_lpdf: Scale parameter is inf, but must be positive finite! (in 'task1.weighted.avg.stan', line 58, column 4 to column 67)
	Exception: task1x46weightedx46avg_model_namespace::log_prob: theta[31] is nan, but must be greater than or equal to 0.000000 (in 'task1.weighted.avg.stan', line 31, column 2 to column 36)
Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in 'task1.weighted.avg.stan', line 57, column 4 to column 47)
	Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in 'task1.weighted.avg.stan', line 57, column 4 to column 47)
	Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in 'task1.weighted.avg.stan', line 57, column 4 to column 47)
	Exception: normal_lpdf: Scale parameter is 0, but must be positive! (in 'task1.weighted.avg.stan', line 57, column 4 to column 47)
	Exception: task1x46weightedx46avg_model_namespace::log_prob: theta[21] is nan, but must be greater than or equal to 0.000000 (in 'task1.weighted.avg.stan', line 31, column 2 to column 36)
Consider re-running with show_console=True if the above output is unclear!

12:50:32 - cmdstanpy - WARNING - Some chains may have failed to converge.
	Chain 2 had 2 divergent transitions (0.1%)
	Chain 3 had 710 divergent transitions (17.8%)
	Chain 4 had 34 divergent transitions (0.9%)
	Use the "diagnose()" method on the CmdStanMCMC object to see further information.

Note that some chains have failed to converge.

In [43]:
fit1.diagnose()

"Checking sampler transitions treedepth.\nTreedepth satisfactory for all transitions.\n\nChecking sampler transitions for divergences.\n234 of 16000 (1.46%) transitions ended with a divergence.\nThese divergent transitions indicate that HMC is not fully able to explore the posterior distribution.\nTry increasing adapt delta closer to 1.\nIf this doesn't remove all divergences, try to reparameterize the model.\n\nChecking E-BFMI - sampler transitions HMC potential energy.\nE-BFMI satisfactory.\n\nRank-normalized split effective sample size satisfactory for all parameters.\n\nRank-normalized split R-hat values satisfactory for all parameters.\n\nProcessing complete.\n"

In [46]:
# Translate to InferenceData 

task1_idata = az.from_cmdstanpy(fit1)
task1_idata

Inference data with groups:
	> posterior
	> log_likelihood
	> sample_stats

In [47]:
# we could try to plot things ...? 

az.summary(task1_idata)

/Users/shenglong/Downloads/vis-decode-analysis/.venv/lib/python3.13/site-packages/arviz/stats/diagnostics.py:596: RuntimeWarning: invalid value encountered in scalar divide
  (between_chain_variance / within_chain_variance + num_samples - 1) / (num_samples)
/Users/shenglong/Downloads/vis-decode-analysis/.venv/lib/python3.13/site-packages/arviz/stats/diagnostics.py:991: RuntimeWarning: invalid value encountered in scalar divide
  varsd = varvar / evar / 4

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
mu_mod_mean,0.005,0.018,-0.027,0.039,0.000,0.000,6602.0,10367.0,1.00
mu_mod_sd,0.047,0.024,0.002,0.086,0.002,0.002,95.0,16.0,1.04
mu_med_mean,0.053,0.050,-0.045,0.146,0.001,0.001,3890.0,8165.0,1.01
mu_med_sd,0.130,0.053,0.024,0.222,0.003,0.001,325.0,762.0,1.02
log_sigma_mod_mean,-1.493,0.092,-1.674,-1.326,0.001,0.001,14076.0,11583.0,1.01
...,...,...,...,...,...,...,...,...,...
x_org[155],7.272,0.000,7.272,7.272,0.000,0.000,16000.0,16000.0,NaN
x_org[156],7.608,0.000,7.608,7.608,0.000,0.000,16000.0,16000.0,NaN
x_org[157],7.457,0.000,7.457,7.457,0.000,0.000,16000.0,16000.0,NaN
x_org[158],6.623,0.000,6.623,6.623,0.000,0.000,16000.0,16000.0,NaN
x_org[159],6.089,0.000,6.089,6.089,0.000,0.000,16000.0,16000.0,NaN

## `task1.weighted.avg.nonc.stan` 

- non-centered parameterization

In [48]:
task1_mix_stanfile = os.path.join('../stan_files/', "task1.weighted.avg.nonc.stan")
task1_model = CmdStanModel(stan_file=task1_mix_stanfile)

12:52:57 - cmdstanpy - INFO - compiling stan file /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc.stan to exe file /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc
12:53:03 - cmdstanpy - INFO - compiled model executable: /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc

In [49]:
# use shutil to move things around
dest_dir = "../stan_bin_files"
shutil.move(task1_model.exe_file, os.path.join(dest_dir, task1_model.name))
task1_model = CmdStanModel(exe_file=os.path.join(dest_dir, task1_model.name))

In [52]:
# sample 
fit2 = task1_model.sample(
    data = stan_data, 
    chains=4, 
    parallel_chains=4, 
    iter_warmup=2000,
    iter_sampling=4000,
    adapt_delta=0.95, 
    show_console=True,
)

12:54:20 - cmdstanpy - INFO - Chain [1] start processing
12:54:20 - cmdstanpy - INFO - Chain [2] start processing
12:54:20 - cmdstanpy - INFO - Chain [3] start processing
12:54:20 - cmdstanpy - INFO - Chain [4] start processing

Chain [1] method = sample (Default)
Chain [1] sample
Chain [1] num_samples = 4000
Chain [1] num_warmup = 2000
Chain [1] save_warmup = false (Default)
Chain [1] thin = 1 (Default)
Chain [1] adapt
Chain [1] engaged = true (Default)
Chain [1] gamma = 0.05 (Default)
Chain [1] delta = 0.95
Chain [1] kappa = 0.75 (Default)
Chain [1] t0 = 10 (Default)
Chain [1] init_buffer = 75 (Default)
Chain [1] term_buffer = 50 (Default)
Chain [1] window = 25 (Default)
Chain [1] save_metric = false (Default)
Chain [1] algorithm = hmc (Default)
Chain [1] hmc
Chain [2] method = sample (Default)
Chain [2] sample
Chain [2] num_samples = 4000
Chain [2] num_warmup = 2000
Chain [2] save_warmup = false (Default)
Chain [2] thin = 1 (Default)
Chain [2] adapt
Chain [2] engaged = true (Default)
Chain [2] gamma = 0.05 (Default)
Chain [2] delta = 0.95
Chain [2] kappa = 0.75 (Default)
Chain [2] t0 = 10 (Default)
Chain [2] init_buffer = 75 (Default)
Chain [2] term_buffer = 50 (Default)
Chain [2] window = 25 (Default)
Chain [2] save_metric = false (Default)
Chain [2] algorithm = hmc (Default)
Chain [2] hmc
Chain [2] engine = nuts (Default)
Chain [1] engine = nuts (Default)
Chain [1] nuts
Chain [1] max_depth = 10 (Default)
Chain [1] metric = diag_e (Default)
Chain [1] metric_file =  (Default)
Chain [1] stepsize = 1 (Default)
Chain [1] stepsize_jitter = 0 (Default)
Chain [1] num_chains = 1 (Default)
Chain [1] id = 1 (Default)
Chain [1] data
Chain [1] file = /var/folders/xz/hg6l5mzj2wnb8mr2q4slgnr40000gn/T/tmp1znfvew4/khtkdvvd.json
Chain [1] init = 2 (Default)
Chain [1] random
Chain [1] seed = 23140
Chain [2] nuts
Chain [2] max_depth = 10 (Default)
Chain [2] metric = diag_e (Default)
Chain [2] metric_file =  (Default)
Chain [2] stepsize = 1 (Default)
Chain [2] stepsize_jitter = 0 (Default)
Chain [2] num_chains = 1 (Default)
Chain [2] id = 2
Chain [2] data
Chain [2] file = /var/folders/xz/hg6l5mzj2wnb8mr2q4slgnr40000gn/T/tmp1znfvew4/khtkdvvd.json
Chain [2] init = 2 (Default)
Chain [2] random
Chain [2] seed = 23140
Chain [2] output
Chain [2] file = /var/folders/xz/hg6l5mzj2wnb8mr2q4slgnr40000gn/T/tmp1znfvew4/task1.weighted.avg61gsqie9/task1.weighted.avg-20260121125420_2.csv
Chain [2] diagnostic_file =  (Default)
Chain [2] refresh = 100 (Default)
Chain [2] sig_figs = 8 (Default)
Chain [2] profile_file = profile.csv (Default)
Chain [2] save_cmdstan_config = false (Default)
Chain [2] num_threads = 1 (Default)
Chain [2]
Chain [2]
Chain [2] Gradient evaluation took 5.9e-05 seconds
Chain [2] 1000 transitions using 10 leapfrog steps per transition would take 0.59 seconds.
Chain [2] Adjust your expectations accordingly!
Chain [2]
Chain [2]
Chain [2] Iteration:    1 / 6000 [  0%]  (Warmup)
Chain [2] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [2] Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [2] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [2] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [2]
Chain [1] output
Chain [1] file = /var/folders/xz/hg6l5mzj2wnb8mr2q4slgnr40000gn/T/tmp1znfvew4/task1.weighted.avg61gsqie9/task1.weighted.avg-20260121125420_1.csv
Chain [1] diagnostic_file =  (Default)
Chain [1] refresh = 100 (Default)
Chain [1] sig_figs = 8 (Default)
Chain [1] profile_file = profile.csv (Default)
Chain [1] save_cmdstan_config = false (Default)
Chain [1] num_threads = 1 (Default)
Chain [1]
Chain [1]
Chain [1] Gradient evaluation took 0.000176 seconds
Chain [1] 1000 transitions using 10 leapfrog steps per transition would take 1.76 seconds.
Chain [1] Adjust your expectations accordingly!
Chain [1]
Chain [1]
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [1] Iteration:    1 / 6000 [  0%]  (Warmup)
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [1] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [1] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [1] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [1] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [1]
Chain [3] method = sample (Default)
Chain [3] sample
Chain [3] num_samples = 4000
Chain [3] num_warmup = 2000
Chain [3] save_warmup = false (Default)
Chain [3] thin = 1 (Default)
Chain [3] adapt
Chain [3] engaged = true (Default)
Chain [3] gamma = 0.05 (Default)
Chain [3] delta = 0.95
Chain [3] kappa = 0.75 (Default)
Chain [3] t0 = 10 (Default)
Chain [3] init_buffer = 75 (Default)
Chain [3] term_buffer = 50 (Default)
Chain [3] window = 25 (Default)
Chain [3] save_metric = false (Default)
Chain [3] algorithm = hmc (Default)
Chain [3] hmc
Chain [3] engine = nuts (Default)
Chain [3] nuts
Chain [3] max_depth = 10 (Default)
Chain [3] metric = diag_e (Default)
Chain [3] metric_file =  (Default)
Chain [3] stepsize = 1 (Default)
Chain [3] stepsize_jitter = 0 (Default)
Chain [3] num_chains = 1 (Default)
Chain [3] id = 3
Chain [3] data
Chain [3] file = /var/folders/xz/hg6l5mzj2wnb8mr2q4slgnr40000gn/T/tmp1znfvew4/khtkdvvd.json
Chain [3] init = 2 (Default)
Chain [3] random
Chain [3] seed = 23140
Chain [3] output
Chain [3] file = /var/folders/xz/hg6l5mzj2wnb8mr2q4slgnr40000gn/T/tmp1znfvew4/task1.weighted.avg61gsqie9/task1.weighted.avg-20260121125420_3.csv
Chain [3] diagnostic_file =  (Default)
Chain [3] refresh = 100 (Default)
Chain [3] sig_figs = 8 (Default)
Chain [3] profile_file = profile.csv (Default)
Chain [3] save_cmdstan_config = false (Default)
Chain [3] num_threads = 1 (Default)
Chain [3]
Chain [3]
Chain [3] Gradient evaluation took 5.8e-05 seconds
Chain [3] 1000 transitions using 10 leapfrog steps per transition would take 0.58 seconds.
Chain [3] Adjust your expectations accordingly!
Chain [3]
Chain [3]
Chain [3] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [3] Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [3] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [3] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [3]
Chain [3] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [3] Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [3] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [3] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [3]
Chain [3] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [3] Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [3] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [3] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [3]
Chain [3] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [3] Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [3] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [3] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [3]
Chain [3] Iteration:    1 / 6000 [  0%]  (Warmup)
Chain [3] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [3] Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [3] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [3] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [3]
Chain [4] method = sample (Default)
Chain [4] sample
Chain [4] num_samples = 4000
Chain [4] num_warmup = 2000
Chain [4] save_warmup = false (Default)
Chain [4] thin = 1 (Default)
Chain [4] adapt
Chain [4] engaged = true (Default)
Chain [4] gamma = 0.05 (Default)
Chain [4] delta = 0.95
Chain [4] kappa = 0.75 (Default)
Chain [4] t0 = 10 (Default)
Chain [4] init_buffer = 75 (Default)
Chain [4] term_buffer = 50 (Default)
Chain [4] window = 25 (Default)
Chain [4] save_metric = false (Default)
Chain [4] algorithm = hmc (Default)
Chain [4] hmc
Chain [4] engine = nuts (Default)
Chain [4] nuts
Chain [4] max_depth = 10 (Default)
Chain [4] metric = diag_e (Default)
Chain [4] metric_file =  (Default)
Chain [4] stepsize = 1 (Default)
Chain [4] stepsize_jitter = 0 (Default)
Chain [4] num_chains = 1 (Default)
Chain [4] id = 4
Chain [4] data
Chain [4] file = /var/folders/xz/hg6l5mzj2wnb8mr2q4slgnr40000gn/T/tmp1znfvew4/khtkdvvd.json
Chain [4] init = 2 (Default)
Chain [4] random
Chain [4] seed = 23140
Chain [4] output
Chain [4] file = /var/folders/xz/hg6l5mzj2wnb8mr2q4slgnr40000gn/T/tmp1znfvew4/task1.weighted.avg61gsqie9/task1.weighted.avg-20260121125420_4.csv
Chain [4] diagnostic_file =  (Default)
Chain [4] refresh = 100 (Default)
Chain [4] sig_figs = 8 (Default)
Chain [4] profile_file = profile.csv (Default)
Chain [4] save_cmdstan_config = false (Default)
Chain [4] num_threads = 1 (Default)
Chain [4]
Chain [4]
Chain [4] Gradient evaluation took 8e-05 seconds
Chain [4] 1000 transitions using 10 leapfrog steps per transition would take 0.8 seconds.
Chain [4] Adjust your expectations accordingly!
Chain [4]
Chain [4]
Chain [4] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [4] Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [4] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [4] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [4]
Chain [4] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [4] Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Chain [4] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [4] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [4]
Chain [4] Iteration:    1 / 6000 [  0%]  (Warmup)
Chain [4] Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Chain [4] Exception: task1x46weightedx46avgx46nonc_model_namespace::log_prob: theta[11] is nan, but must be greater than or equal to 0.000000 (in 'task1.weighted.avg.nonc.stan', line 42, column 2 to column 36)
Chain [4] If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
Chain [4] but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
Chain [4]
Chain [1] Iteration:  100 / 6000 [  1%]  (Warmup)
Chain [1] Iteration:  200 / 6000 [  3%]  (Warmup)
Chain [3] Iteration:  100 / 6000 [  1%]  (Warmup)
Chain [2] Iteration:  100 / 6000 [  1%]  (Warmup)
Chain [4] Iteration:  100 / 6000 [  1%]  (Warmup)
Chain [1] Iteration:  300 / 6000 [  5%]  (Warmup)
Chain [3] Iteration:  200 / 6000 [  3%]  (Warmup)
Chain [2] Iteration:  200 / 6000 [  3%]  (Warmup)
Chain [1] Iteration:  400 / 6000 [  6%]  (Warmup)
Chain [4] Iteration:  200 / 6000 [  3%]  (Warmup)
Chain [3] Iteration:  300 / 6000 [  5%]  (Warmup)
Chain [2] Iteration:  300 / 6000 [  5%]  (Warmup)
Chain [3] Iteration:  400 / 6000 [  6%]  (Warmup)
Chain [1] Iteration:  500 / 6000 [  8%]  (Warmup)
Chain [4] Iteration:  300 / 6000 [  5%]  (Warmup)
Chain [2] Iteration:  400 / 6000 [  6%]  (Warmup)
Chain [1] Iteration:  600 / 6000 [ 10%]  (Warmup)
Chain [4] Iteration:  400 / 6000 [  6%]  (Warmup)
Chain [3] Iteration:  500 / 6000 [  8%]  (Warmup)
Chain [2] Iteration:  500 / 6000 [  8%]  (Warmup)
Chain [1] Iteration:  700 / 6000 [ 11%]  (Warmup)
Chain [3] Iteration:  600 / 6000 [ 10%]  (Warmup)
Chain [4] Iteration:  500 / 6000 [  8%]  (Warmup)
Chain [2] Iteration:  600 / 6000 [ 10%]  (Warmup)
Chain [1] Iteration:  800 / 6000 [ 13%]  (Warmup)
Chain [3] Iteration:  700 / 6000 [ 11%]  (Warmup)
Chain [4] Iteration:  600 / 6000 [ 10%]  (Warmup)
Chain [2] Iteration:  700 / 6000 [ 11%]  (Warmup)
Chain [1] Iteration:  900 / 6000 [ 15%]  (Warmup)
Chain [4] Iteration:  700 / 6000 [ 11%]  (Warmup)
Chain [3] Iteration:  800 / 6000 [ 13%]  (Warmup)
Chain [1] Iteration: 1000 / 6000 [ 16%]  (Warmup)
Chain [2] Iteration:  800 / 6000 [ 13%]  (Warmup)
Chain [4] Iteration:  800 / 6000 [ 13%]  (Warmup)
Chain [1] Iteration: 1100 / 6000 [ 18%]  (Warmup)
Chain [3] Iteration:  900 / 6000 [ 15%]  (Warmup)
Chain [2] Iteration:  900 / 6000 [ 15%]  (Warmup)
Chain [4] Iteration:  900 / 6000 [ 15%]  (Warmup)
Chain [1] Iteration: 1200 / 6000 [ 20%]  (Warmup)
Chain [2] Iteration: 1000 / 6000 [ 16%]  (Warmup)
Chain [3] Iteration: 1000 / 6000 [ 16%]  (Warmup)
Chain [4] Iteration: 1000 / 6000 [ 16%]  (Warmup)
Chain [1] Iteration: 1300 / 6000 [ 21%]  (Warmup)
Chain [2] Iteration: 1100 / 6000 [ 18%]  (Warmup)
Chain [4] Iteration: 1100 / 6000 [ 18%]  (Warmup)
Chain [3] Iteration: 1100 / 6000 [ 18%]  (Warmup)
Chain [2] Iteration: 1200 / 6000 [ 20%]  (Warmup)
Chain [1] Iteration: 1400 / 6000 [ 23%]  (Warmup)
Chain [4] Iteration: 1200 / 6000 [ 20%]  (Warmup)
Chain [3] Iteration: 1200 / 6000 [ 20%]  (Warmup)
Chain [1] Iteration: 1500 / 6000 [ 25%]  (Warmup)
Chain [2] Iteration: 1300 / 6000 [ 21%]  (Warmup)
Chain [4] Iteration: 1300 / 6000 [ 21%]  (Warmup)
Chain [3] Iteration: 1300 / 6000 [ 21%]  (Warmup)
Chain [1] Iteration: 1600 / 6000 [ 26%]  (Warmup)
Chain [4] Iteration: 1400 / 6000 [ 23%]  (Warmup)
Chain [2] Iteration: 1400 / 6000 [ 23%]  (Warmup)
Chain [3] Iteration: 1400 / 6000 [ 23%]  (Warmup)
Chain [1] Iteration: 1700 / 6000 [ 28%]  (Warmup)
Chain [4] Iteration: 1500 / 6000 [ 25%]  (Warmup)
Chain [2] Iteration: 1500 / 6000 [ 25%]  (Warmup)
Chain [3] Iteration: 1500 / 6000 [ 25%]  (Warmup)
Chain [1] Iteration: 1800 / 6000 [ 30%]  (Warmup)
Chain [4] Iteration: 1600 / 6000 [ 26%]  (Warmup)
Chain [2] Iteration: 1600 / 6000 [ 26%]  (Warmup)
Chain [3] Iteration: 1600 / 6000 [ 26%]  (Warmup)

12:54:30 - cmdstanpy - INFO - Chain [2] done processing

Chain [4] Iteration: 5600 / 6000 [ 93%]  (Sampling)
Chain [2] Iteration: 5900 / 6000 [ 98%]  (Sampling)
Chain [1] Iteration: 4300 / 6000 [ 71%]  (Sampling)
Chain [2] Iteration: 6000 / 6000 [100%]  (Sampling)
Chain [2]
Chain [2] Elapsed Time: 4.419 seconds (Warm-up)
Chain [2] 5.109 seconds (Sampling)
Chain [2] 9.528 seconds (Total)
Chain [2]
Chain [4] Iteration: 5700 / 6000 [ 95%]  (Sampling)
Chain [2]
Chain [2]
Chain [3] Iteration: 4200 / 6000 [ 70%]  (Sampling)
Chain [4] Iteration: 5800 / 6000 [ 96%]  (Sampling)
Chain [1] Iteration: 4400 / 6000 [ 73%]  (Sampling)
Chain [3] Iteration: 4300 / 6000 [ 71%]  (Sampling)
Chain [4] Iteration: 5900 / 6000 [ 98%]  (Sampling)

12:54:30 - cmdstanpy - INFO - Chain [4] done processing

Chain [1] Iteration: 4500 / 6000 [ 75%]  (Sampling)
Chain [4] Iteration: 6000 / 6000 [100%]  (Sampling)
Chain [4]
Chain [4] Elapsed Time: 4.364 seconds (Warm-up)
Chain [4] 5.536 seconds (Sampling)
Chain [4] 9.9 seconds (Total)
Chain [4]
Chain [4]
Chain [3] Iteration: 4400 / 6000 [ 73%]  (Sampling)
Chain [1] Iteration: 4600 / 6000 [ 76%]  (Sampling)
Chain [3] Iteration: 4500 / 6000 [ 75%]  (Sampling)
Chain [1] Iteration: 4700 / 6000 [ 78%]  (Sampling)
Chain [3] Iteration: 4600 / 6000 [ 76%]  (Sampling)
Chain [1] Iteration: 4800 / 6000 [ 80%]  (Sampling)
Chain [3] Iteration: 4700 / 6000 [ 78%]  (Sampling)
Chain [1] Iteration: 4900 / 6000 [ 81%]  (Sampling)
Chain [3] Iteration: 4800 / 6000 [ 80%]  (Sampling)
Chain [1] Iteration: 5000 / 6000 [ 83%]  (Sampling)
Chain [3] Iteration: 4900 / 6000 [ 81%]  (Sampling)
Chain [1] Iteration: 5100 / 6000 [ 85%]  (Sampling)
Chain [3] Iteration: 5000 / 6000 [ 83%]  (Sampling)
Chain [1] Iteration: 5200 / 6000 [ 86%]  (Sampling)
Chain [3] Iteration: 5100 / 6000 [ 85%]  (Sampling)
Chain [1] Iteration: 5300 / 6000 [ 88%]  (Sampling)
Chain [3] Iteration: 5200 / 6000 [ 86%]  (Sampling)
Chain [1] Iteration: 5400 / 6000 [ 90%]  (Sampling)
Chain [3] Iteration: 5300 / 6000 [ 88%]  (Sampling)
Chain [1] Iteration: 5500 / 6000 [ 91%]  (Sampling)
Chain [3] Iteration: 5400 / 6000 [ 90%]  (Sampling)
Chain [1] Iteration: 5600 / 6000 [ 93%]  (Sampling)
Chain [3] Iteration: 5500 / 6000 [ 91%]  (Sampling)
Chain [1] Iteration: 5700 / 6000 [ 95%]  (Sampling)
Chain [3] Iteration: 5600 / 6000 [ 93%]  (Sampling)
Chain [1] Iteration: 5800 / 6000 [ 96%]  (Sampling)
Chain [3] Iteration: 5700 / 6000 [ 95%]  (Sampling)
Chain [1] Iteration: 5900 / 6000 [ 98%]  (Sampling)
Chain [3] Iteration: 5800 / 6000 [ 96%]  (Sampling)
Chain [1] Iteration: 6000 / 6000 [100%]  (Sampling)

12:54:33 - cmdstanpy - INFO - Chain [1] done processing

Chain [1]
Chain [1] Elapsed Time: 4.198 seconds (Warm-up)
Chain [1] 8.705 seconds (Sampling)
Chain [1] 12.903 seconds (Total)
Chain [1]
Chain [1]
Chain [3] Iteration: 5900 / 6000 [ 98%]  (Sampling)

12:54:33 - cmdstanpy - INFO - Chain [3] done processing
12:54:33 - cmdstanpy - WARNING - Non-fatal error during sampling:
Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Location parameter is nan, but must be finite! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: normal_lpdf: Scale parameter is nan, but must be positive! (in 'task1.weighted.avg.nonc.stan', line 75, column 4 to line 76, column 126)
	Exception: task1x46weightedx46avgx46nonc_model_namespace::log_prob: theta[11] is nan, but must be greater than or equal to 0.000000 (in 'task1.weighted.avg.nonc.stan', line 42, column 2 to column 36)

Chain [3] Iteration: 6000 / 6000 [100%]  (Sampling)
Chain [3]
Chain [3] Elapsed Time: 4.491 seconds (Warm-up)
Chain [3] 8.733 seconds (Sampling)
Chain [3] 13.224 seconds (Total)
Chain [3]
Chain [3]
Chain [3]

In [53]:
task1_idata = az.from_cmdstanpy(fit2)
task1_idata

Inference data with groups:
	> posterior
	> log_likelihood
	> sample_stats

In [54]:
az.summary(task1_idata)

/Users/shenglong/Downloads/vis-decode-analysis/.venv/lib/python3.13/site-packages/arviz/stats/diagnostics.py:596: RuntimeWarning: invalid value encountered in scalar divide
  (between_chain_variance / within_chain_variance + num_samples - 1) / (num_samples)
/Users/shenglong/Downloads/vis-decode-analysis/.venv/lib/python3.13/site-packages/arviz/stats/diagnostics.py:991: RuntimeWarning: invalid value encountered in scalar divide
  varsd = varvar / evar / 4

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
mu_mod_mean,0.005,0.018,-0.028,0.039,0.000,0.000,19960.0,12381.0,1.0
mu_mod_sd,0.048,0.024,0.002,0.088,0.000,0.000,7693.0,5696.0,1.0
mu_med_mean,0.053,0.052,-0.046,0.148,0.001,0.000,5101.0,9401.0,1.0
mu_med_sd,0.128,0.052,0.017,0.223,0.001,0.001,2557.0,2398.0,1.0
log_sigma_mod_mean,-1.495,0.093,-1.672,-1.323,0.001,0.001,18730.0,13038.0,1.0
...,...,...,...,...,...,...,...,...,...
x_org[155],7.272,0.000,7.272,7.272,0.000,0.000,16000.0,16000.0,NaN
x_org[156],7.608,0.000,7.608,7.608,0.000,0.000,16000.0,16000.0,NaN
x_org[157],7.457,0.000,7.457,7.457,0.000,0.000,16000.0,16000.0,NaN
x_org[158],6.623,0.000,6.623,6.623,0.000,0.000,16000.0,16000.0,NaN
x_org[159],6.089,0.000,6.089,6.089,0.000,0.000,16000.0,16000.0,NaN

In [ ]:
# TODO: get the posterior

## `task1.weighted.avg.nonc.normal.stan`

In [13]:
task1_mix_stanfile = os.path.join('../stan_files/', "task1.weighted.avg.nonc.normal.stan")
task1_model = CmdStanModel(stan_file=task1_mix_stanfile)

16:52:02 - cmdstanpy - INFO - compiling stan file /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc.normal.stan to exe file /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc.normal
16:52:19 - cmdstanpy - INFO - compiled model executable: /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc.normal

In [14]:
# use shutil to move executable to untracked folder around
dest_dir = "../stan_bin_files"
shutil.move(task1_model.exe_file, os.path.join(dest_dir, task1_model.name))
task1_model = CmdStanModel(exe_file=os.path.join(dest_dir, task1_model.name))

In [15]:
# TODO

In [ ]:
# TODO

---

## `task1.mix.stan` 

--- hmm apparently this one doesn't compile because the original definition is a bit wrong ...???

In [ ]:
# task1_mix_stanfile = os.path.join('../stan_files/', "task1.weighted.avg.nonc.normal.stan")
# task1_model = CmdStanModel(stan_file=task1_mix_stanfile)

15:02:34 - cmdstanpy - INFO - compiling stan file /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc.normal.stan to exe file /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc.normal
15:02:40 - cmdstanpy - INFO - compiled model executable: /Users/shenglong/Downloads/vis-decode-analysis/analysis/stan_files/task1.weighted.avg.nonc.normal